### ISSUE TITLE
ImproperlyConfigured: Could not build relationship between Transaction and User.

### ISSUE THREAD

**Issue by mapleoin** [kvesteri/sqlalchemy-continuum#101]
I'm just trying to get started using the sample code provided, but I'm getting this traceback:

```
$ python hello.py 
Traceback (most recent call last):
  File "hello.py", line 20, in <module>
    sa.orm.configure_mappers()
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2736, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy/orm/events.py", line 550, in wrap
    fn(*arg, **kw)
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 159, in configure_versioned_classes
    self.build_transaction_class()
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 139, in build_transaction_class
    self.manager.create_transaction_model()
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy_continuum/manager.py", line 155, in create_transaction_model
    self.transaction_cls = self.transaction_cls(self)
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy_continuum/factory.py", line 11, in __call__
    return self.create_class(manager)
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy_continuum/transaction.py", line 117, in create_class
    TransactionBase
  File "/home/mapleoin/sandbox/continuum/venv/lib/python2.7/site-packages/sqlalchemy_continuum/transaction.py", line 144, in Transaction
    'relationship ' % (user_cls, user_cls)
sqlalchemy_continuum.exc.ImproperlyConfigured: Could not build relationship between Transaction and User. User was not found in declarative class registry. Either configure VersioningManager to use different user class or disable this relationship 
```

```python
# hello.py 
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy_continuum import make_versioned

Base = declarative_base()

make_versioned()


class Article(Base):
    __versioned__ = {}
    __tablename__ = 'article'

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    name = sa.Column(sa.Unicode(255))
    content = sa.Column(sa.UnicodeText)


# after you have defined all your models, call configure_mappers:
sa.orm.configure_mappers()
```

```
$ pip freeze
psycopg2==2.6.1
six==1.9.0
SQLAlchemy==1.0.8
SQLAlchemy-Continuum==1.2.0
SQLAlchemy-Utils==0.30.16
```

**Comment by zlhgo** [comment]
make_versioned(user_cls=None)
