### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: Implicitly combining column(...) in joined table inheritance scenario

### ISSUE THREAD

**Issue by piotr-dobrogost** [kvesteri/sqlalchemy-continuum#105]
When I tried to version tables from Kotti project I [encountered](https://github.com/Kotti/Kotti/issues/265#issuecomment-137053295) `sqlalchemy.exc.InvalidRequestError: Implicitly combining column(...)` error. Below is a test case showing the problem and a traceback. When turning debug logs on, the last few entries before exception are as follows:
> INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(operation_type, ColumnProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(transaction_id, ColumnProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(end_transaction_id, ColumnProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(id, ColumnProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(type, ColumnProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(version_parent, RelationshipProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(transaction, RelationshipProperty)
INFO:sqlalchemy.orm.mapper.Mapper:(DocumentVersion|documents_version) _configure_property(transaction_id, Column)

Reading [I’m getting a warning or error about “Implicitly combining column X under attribute Y”](http://docs.sqlalchemy.org/en/latest/faq/ormconfiguration.html#i-m-getting-a-warning-or-error-about-implicitly-combining-column-x-under-attribute-y) entry in the SQLAlchemy's FAQ I get impression that `transaction_id` property should only be configured as `ColumnProperty` not `Column`. The fact it's the only property in this model which is configured twice, each time with different type looks suspicious.

Thank you in advance for any help.

SQLAlchemy-Continuum 1.2.0, SQLAlchemy 1.0.8

```python
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import UnicodeText
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import configure_mappers
from sqlalchemy.util import classproperty

from sqlalchemy_continuum import make_versioned

make_versioned(user_cls=None)


class MyBase(object):
    @declared_attr
    def __tablename__(cls):
        return '{0}s'.format(cls.__name__.lower())


Base = declarative_base(cls=MyBase)


class Node(Base):
    __versioned__ = {}

    __mapper_args__ = dict(
        polymorphic_on='type',
        polymorphic_identity='node',
        with_polymorphic='*',
        )

    id = Column(Integer(), primary_key=True)
    type = Column(String(30), nullable=False)


class Content(Node):
    __versioned__ = {}

    @classproperty
    def __mapper_args__(cls):
        return dict(polymorphic_identity=cls.__name__.lower())

    id = Column(Integer, ForeignKey('nodes.id'), primary_key=True)
    description = Column(UnicodeText())


class Document(Content):
    __versioned__ = {}

    id = Column(Integer(), ForeignKey('contents.id'), primary_key=True)
    body = Column(UnicodeText())


configure_mappers()
```

```python
/home/piotr/projects/kotti-versioning/env/bin/python /home/piotr/projects/kotti-versioning/test.py
Traceback (most recent call last):
  File "/home/piotr/projects/kotti-versioning/test.py", line 56, in <module>
    configure_mappers()
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2736, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/orm/events.py", line 550, in wrap
    fn(*arg, **kw)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 165, in configure_versioned_classes
    self.build_models()
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 87, in build_models
    self.manager.transaction_cls
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy_continuum/model_builder.py", line 263, in __call__
    self.version_class = self.build_model(table)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy_continuum/model_builder.py", line 250, in build_model
    args
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 55, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 135, in __init__
    self._early_mapping()
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 138, in _early_mapping
    self.map()
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 529, in map
    **self.mapper_args
  File "<string>", line 2, in mapper
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 627, in __init__
    self._configure_properties()
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1318, in _configure_properties
    setparent=True)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1525, in _configure_property
    prop = self._property_from_column(key, prop)
  File "/home/piotr/projects/kotti-versioning/env/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1650, in _property_from_column
    raise sa_exc.InvalidRequestError(msg)
sqlalchemy.exc.InvalidRequestError: Implicitly combining column contents_version.transaction_id with column nodes_version.transaction_id under attribute 'transaction_id'.  Please configure one or more attributes for these same-named columns explicitly.

Process finished with exit code 1
```

**Comment by filwaitman** [comment]
:+1: 

Happening with me as well. Seems like problem is when a multi-level inheritance is present - and versioning is on root class.

I'm gonna test it again using the branch for https://github.com/kvesteri/sqlalchemy-continuum/pull/106. I'll post my comments here and on https://github.com/kvesteri/sqlalchemy-continuum/pull/106 itself.

**Comment by filwaitman** [comment]
Unfortunately, it didn't work for me. :cry: 

See details in https://github.com/kvesteri/sqlalchemy-continuum/pull/106#issuecomment-142690325.

**Comment by filwaitman** [comment]
Like I said in https://github.com/kvesteri/sqlalchemy-continuum/pull/106#issuecomment-142705365: The PR worked like a charm!  =]

Thank you!
