### ISSUE TITLE
user_cls primary key different from id causes error

### ISSUE THREAD

**Issue by avilaton** [kvesteri/sqlalchemy-continuum#107]
Hi, 

I tryed versioning a single table in a project using flask and I got an error 
```
sqlalchemy.exc.NoReferencedColumnError: Could not initialize target column for ForeignKey 'users.id' on table 'transaction': table 'users' has no column named 'id'
```
where my users table has the following shape
```
class User(db.Model):
    __tablename__ = "users"
    user_id = db.Column('user_id', db.Integer, primary_key=True)
    password_hash = db.Column(db.String(128))
    email = db.Column('email',db.String(50),unique=True , index=True)
    registered_on = db.Column(db.DateTime(), default=datetime.utcnow)
```
I tryed feeding the FlaskPlugin with a factory that would return the correct value but that did not work.
I guess it has to do with this line in the code
https://github.com/kvesteri/sqlalchemy-continuum/blob/master/sqlalchemy_continuum/transaction.py#L150
to which I will submit a PR. 

Here is the full stack trace:
```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    from app.models import *
  File "/home/gavila/tonTrabajo/google-transit/develop/gtfseditor/app/models.py", line 349, in <module>
    sa.orm.configure_mappers()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2736, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/events.py", line 550, in wrap
    fn(*arg, **kw)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 171, in configure_versioned_classes
    self.build_relationships(pending_copy)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 107, in build_relationships
    for prop in sa.inspect(cls).iterate_properties:
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1819, in iterate_properties
    configure_mappers()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2721, in configure_mappers
    mapper._post_configure_properties()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1710, in _post_configure_properties
    prop.init()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/interfaces.py", line 183, in init
    self.do_init()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1617, in do_init
    self._setup_join_conditions()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1692, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1960, in __init__
    self._determine_joins()
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 2043, in _determine_joins
    consider_as_foreign_keys=consider_as_foreign_keys
  File "<string>", line 2, in join_condition
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 824, in _join_condition
    a, a_subset, b, consider_as_foreign_keys)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 879, in _joincond_scan_left_right
    col = fk.get_referent(b)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1644, in get_referent
    return table.corresponding_column(self.column)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 747, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/gavila/.virtualenvs/gtfs/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1795, in column
    tablekey, colname)
sqlalchemy.exc.NoReferencedColumnError: Could not initialize target column for ForeignKey 'users.id' on table 'transaction': table 'users' has no column named 'id'
```

**Comment by piotr-dobrogost** [comment]
Sorry for hijacking this issue but how does relation to User class in Continuum is supposed to work? I mean how does Continuum would know which user did modifications in given transaction?

**Comment by avilaton** [comment]
It interacts with flask through the flask-plugin. See 
https://sqlalchemy-continuum.readthedocs.org/en/latest/plugins.html#module-sqlalchemy_continuum.plugins.flask
and 
https://github.com/kvesteri/sqlalchemy-continuum/blob/master/sqlalchemy_continuum/plugins/flask.py

**Comment by piotr-dobrogost** [comment]
Thank you – this was the missing piece I needed. Based on FlaskPlugin I created plugin for Pyramid.
