### ISSUE TITLE
Issue with revisions table already defined for MetaData instance.

### ISSUE THREAD

**Issue by born2discover** [kvesteri/sqlalchemy-continuum#140]
Hello @kvesteri,
First of all thank you for this module, it really does simply the versioning.

However I ran into an issue which I am unable to resolve and there is nothing mentioned about this in the docs, so here I am hoping that maybe somebody here or yourself might have an idea on what's wrong.

I am trying to use sqlalchemy-continuum in a Flask (with Flask-SQLAlchemy) application that operates on a database. As the database already exists, all my models inherit reflected metadata:

```python
# ...
from sqlalchemy_continuum.plugins import FlaskPlugin
from sqlalchemy_continuum import make_versioned

# Required for using existing tables within the databse.
with app.app_context():
    db.Model.metadata.reflect(db.engine)

make_versioned(plugins=[FlaskPlugin()])

class User(db.Model):
    __versioned__ = {}
    __table__ = __tablename__ = db.Model.metadata.tables['forum_users']

sqlalchemy.orm.configure_mappers()
```

However whenever I try to launch the application I get the following error every time (except on the first request when table is not present in the database).
````
Traceback (most recent call last):
File "app/models.py", line 93, in <module>
    sqlalchemy.orm.configure_mappers()
  File ".venv/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 2783, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File ".venv/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File ".venv/lib/python3.5/site-packages/sqlalchemy/orm/events.py", line 614, in wrap
    fn(*arg, **kw)
  File ".venv/lib/python3.5/site-packages/sqlalchemy_continuum/builder.py", line 158, in configure_versioned_classes
    self.build_tables()
  File ".venv/lib/python3.5/site-packages/sqlalchemy_continuum/builder.py", line 55, in build_tables
    table = builder()
  File ".venv/lib/python3.5/site-packages/sqlalchemy_continuum/table_builder.py", line 153, in __call__
    extend_existing=extends is not None
  File ".venv/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 398, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'forum_users_version' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

Any ideas where this might come from?
Thank you in advance!

**Comment by rdolen** [comment]
@born2discover were you able to figure out a solution to this? I think I may be running into a similar error.
