### ISSUE TITLE
Version table `id` is an `int`.

### ISSUE THREAD

**Issue by fake-name** [kvesteri/sqlalchemy-continuum#158]
Basically, the version table `id` column is just a plain integer. For versioning large tables, this appears to pretty readily get exceeded.

I'd think these should be `bigint`s by default. 

```
[2017-02-14 22:39:00,568] ERROR in app: Exception on /render [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: integer out of range

```

When `id` == `2147765748`.

Alternatively, it should be configurable. My origin table has a `bigint` primary key (because it wound up being required). 

Alternatively, it's possible this is autodetected, and it's somehow not properly been migrated when I upgraded my main table from `int` to `bigint`, but I'd have thought `alembic` would have complained if that were true.

**Comment by fake-name** [comment]
Never mind, I'm just dumb and somehow missed alembic trying to fix the column.
