### ISSUE TITLE
Schema existence probes seem broken in some cases

### ISSUE THREAD

**Issue by fake-name** [kvesteri/sqlalchemy-continuum#177]
Basically, I just updated from 1.2.x to 1.3.3, and the `version_table()` call is now broken. 

```
>>> version_table(common.database.RawWebPages)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy_continuum/utils.py", line 136, in version_table
    if table.schema:
AttributeError: type object 'RawWebPages' has no attribute 'schema'

```

with the table defined as:

```


class RawWebPages(common.db_base.Base):
	__versioned__ = {}

	__tablename__     = 'raw_web_pages'
	name              = 'raw_web_pages'

	id                = Column(BigInteger, primary_key = True, index = True)
	state             = Column(common.db_types.dlstate_enum, default='new', index=True, nullable=False)
	errno             = Column(Integer, default='0')
	url               = Column(Text, nullable = False, index = True, unique = True)
	starturl          = Column(Text, nullable = False)
	netloc            = Column(Text, nullable = False, index = True)

	priority          = Column(Integer, default=1000000, index=True, nullable=False)
	distance          = Column(Integer, index=True, nullable=False)

	mimetype          = Column(Text)

	# Disabled due to disk-space issues.
	# raw_content       = Column(Text)

	filename     = Column(Text)

	fspath       = Column(Text)

	fetchtime         = Column(DateTime, default=datetime.datetime.min)
	addtime           = Column(DateTime, default=datetime.datetime.utcnow)

	ignoreuntiltime   = Column(DateTime, default=datetime.datetime.min, nullable=False)



```

The problem appears to be a result of https://github.com/kvesteri/sqlalchemy-continuum/commit/7089b813c0b31de52c5b30d797a450d16e5f33e0.

I'm actually not sure where the "schema" attribute is supposed to come from, but probing the table class interactively yields:

```
[
	'__class__', 
	'__delattr__', 
	'__dict__', 
	'__dir__', 
	'__doc__', 
	'__eq__', 
	'__format__', 
	'__ge__', 
	'__getattribute__', 
	'__gt__', 
	'__hash__', 
	'__init__', 
	'__le__', 
	'__lt__', 
	'__mapper__', 
	'__module__', 
	'__ne__', 
	'__new__', 
	'__reduce__', 
	'__reduce_ex__', 
	'__repr__', 
	'__setattr__', 
	'__sizeof__', 
	'__str__', 
	'__subclasshook__', 
	'__table__', 
	'__tablename__', 
	'__versioned__', 
	'__versioning_manager__', 
	'__weakref__', 
	'_decl_class_registry', 
	'_sa_class_manager', 
	'addtime', 
	'distance', 
	'errno', 
	'fetchtime', 
	'filename', 
	'fspath', 
	'id', 
	'ignoreuntiltime', 
	'metadata', 
	'mimetype', 
	'name', 
	'netloc', 
	'priority', 
	'starturl', 
	'state', 
	'url', 
	'versions'
]
```

So it's not there. 

I'm not sure how this would ever work in the absense of the `.schema` member. I *assume* the code should actually be:

```
def version_table(table):
    """
    Return associated version table for given SQLAlchemy Table object.

    :param table: SQLAlchemy Table object
    """
    if hasattr(table, "schema"):
        return table.metadata.tables[
            table.schema + '.' + table.name + '_version'
        ]
    elif table.metadata.schema:
        return table.metadata.tables[
            table.metadata.schema + '.' + table.name + '_version'
        ]
    else:
        return table.metadata.tables[
            table.name + '_version'
        ]
```

And hacking the above into my install by just editing the system python files seems to fix the issue. 

That said:

 - How was this ever *supposed* to work? None of my tables have the `schema` member, and it's non-specific enough to be basically impossible to google.

**Comment by fake-name** [comment]
Note that this may imply other portions of https://github.com/kvesteri/sqlalchemy-continuum/pull/132 are broken, since the `if table.schema:` pattern is used elsewhere. Presumably, it will fail there, too.

**Comment by fake-name** [comment]
Looking at the unit tests from https://github.com/kvesteri/sqlalchemy-continuum/pull/132, this appears to work based on the fact that all the tables are defined with an additional table parameter (`schema`). This is however not done in any of the documentation examples. 

Is the plan for this to be a required thing to do for versioned tables in the future? If not, the unit tests should probably test it both ways, so this doesn't reoccur.

**Comment by vault** [comment]
I believe you're using `version_table` wrong. `version_table` takes a `Table` instance as its argument, not a model class. Can you use the `version_class` function instead?

SQLAlchemy `Table` objects should all have a `schema` attribute. It's just `None` unless it's explicitly specified.

```
>>> from sqlalchemy import Table, MetaData
>>> t = Table('test', MetaData())
>>> t.schema is None
True
```

**Comment by vault** [comment]
Although since this used to work, maybe its worth adding detection for this case in `version_table`? @kvesteri would that be reasonable, or is it on the caller to get right?

**Comment by fake-name** [comment]
I've generally been under the impression that touching `__things__` was something of a code smell. 

Is accessing `__table__` a normal operation?

**Comment by vault** [comment]
I'm not aware of a better way to get at the underlying table. It also seems to be what the SQLAlchemy docs are saying to do:

> The resulting table and mapper are accessible via \_\_table\_\_ and \_\_mapper\_\_ attributes on the SomeClass class ([source](http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/basic_use.html?highlight=__table__#basic-use))
