### ISSUE TITLE
Duplicate key value on many-to-many relationship versioning

### ISSUE THREAD

**Issue by okcomp** [kvesteri/sqlalchemy-continuum#178]
I have a many-to-many relationship, here's the models:

```python
class Membership(BaseModel):
    tenant_id = Column(Integer, ForeignKey('tenant.tenant_id', ondelete='CASCADE'), primary_key=True)
    user_id = Column(Integer, ForeignKey('user.user_id', ondelete='CASCADE'), primary_key=True)

class User(BaseModel):
    user_id = Column(Integer, primary_key=True)

class Tenant(BaseModel):
    tenant_id = Column(Integer, primary_key=True)
```

When I tried to create the association model, I got `psycopg2.IntegrityError` error on the versioned membership table. 

```python
>> m = Membership(tenant_id=tenant_id, user_id=user_id)
>> db.session.add(m)
>> db.commit()
```

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "version_membership_pkey"
DETAIL:  Key (tenant_id, user_id, transaction_id)=(1, 1, 2) already exists.
```

Does Continuum support this kind of relationship? Or is there any configuration I'm missing here to get this work?

**Comment by cofinley** [comment]
Bump. I have an association table and having problems with versioning. the `article.version[x].tags` is the same for all versions. I'm guessing because of the default validity strategy and the `end_transaction_id` is not changing from `null`. I'd like to know more about what can be done with association tables and versioning that kind of relationship.

**Comment by cofinley** [comment]
Update: ended up dumping the tag relationship (comma separated) to a string column for the `Article` model. I stopped trying to get versioning to work within the association table. Now I can just parse and dump the relationship to compare versions.

**Comment by ErinMorelli** [comment]
Bumping this issue (@kvesteri) - I'm seeing this same problem with many-to-many relationships.

```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "media_tags_version_pkey"
DETAIL:  Key (media_id, tag_id, transaction_id)=(417, 105, 13) already exists.
 [SQL: 'INSERT INTO media_tags_version (media_id, tag_id, transaction_id, operation_type) VALUES (%(media_id)s, %(tag_id)s, %(transaction_id)s, %(operation_type)s)'] [parameters: {'operation_type': 2, 'media_id': 417, 'tag_id': 105, 'transaction_id': 13L}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

It seems like it's potentially issuing two INSERT statements for the same transaction?

I'm using the basic association table setup and the native_versioning option. Could it be an issue with the triggers? Would love some help debugging. Thanks!

**Comment by ErinMorelli** [comment]
Update:

I ran the `sqlalchemy_continuum.dialects.postgresql.drop_trigger` function on all of my tables and now things are working, but I'm assuming that means I am no longer using the `native_versioning` feature, correct?

If I run `sqlalchemy_continuum.dialects.postgresql.sync_trigger` on all of the tables, the issue returns, so this is clearly where the issues is. Any ideas on a work-around?

**Comment by Simes** [comment]
I'm also having this problem. Does anyone know of a workaround until the issue is fixed? As it's been open for over a year.

**Comment by xg1990** [comment]
the issue is still there.....

**Comment by Simes** [comment]
I didn't put the kludge I come up with into this thread originally because it does seem to be a horrible kludge but as this issue is still ongoing, maybe it'll be helpful to someone. It removes the duplicate statements by the hacky method of putting them into a dictionary and using the stringified version of the statement as the key.

Add the replacement `UnitOfWork` class to your codebase somewhere:

```Python
class UnitOfWork(sqlalchemy_continuum.UnitOfWork):
    """ We replace the function we need to patch, otherwise the superclass still does everything
    """

    def create_association_versions(self, session):
        """
        Creates association table version records for given session.
        :param session: SQLAlchemy session object

        """
        # statements = copy(self.pending_statements)

        # Dedupe statements
        temp = { str(st) : st for st in self.pending_statements }

        statements = temp.values()

        for stmt in statements:
            stmt = stmt.values(
                **{
                    self.manager.options['transaction_column_name']:
                    self.current_transaction.id
                }
            )
            session.execute(stmt)
        self.pending_statements = []
```

Also, right after your call to `make_versioned`, insert the code to replace the supplied `UnitOfWork` class with the patched one:

```Python 
sqlalchemy_continuum.versioning_manager.uow_class = horrible_kludges.UnitOfWork
``` 

I am 100% certain that a better solution than this exists and I am by no means advocating for adding this to Continuum. But it does get rid of the issue, at the cost of additional execution time.

**Comment by maarten-dp** [comment]
I've set up a session listener to create a new transaction when needed. A bit of a workaround, but it seems to work on my end.
Any feedback or improvements are welcome of course.

```python
from sqlalchemy_continuum import versioning_manager
from sqlalchemy_continuum.version import VersionClassBase
from sqlalchemy import event

@event.listens_for(Session, 'before_flush')
def transaction(session, flush_context, instances):
    for target in session.new.union(session.dirty):
        if isinstance(target, VersionClassBase):
            uow = versioning_manager.unit_of_work(session)
            transaction_id = uow.current_transaction.id
            res = session.query(target.__class__).filter_by(transaction_id=transaction_id).all()
            if res:
                # A transaction already exists, so create a new one.
                Transaction = uow.manager.transaction_cls
                uow.current_transaction = Transaction()
                target.transaction = uow.current_transaction
                target.transaction_id = None
```

**Comment by killthekitten** [comment]
@Simes @maarten-dp thanks both of you for proposing the workarounds! Could you also post the migrations that create the version tables that break the transaction? I believe the version tables generated for many-to-many associations are lacking a correct primary key.

Let me give a couple examples. This is a many-to-many versions table:

```python
    op.create_table(
        "foo_bar_versions",
        ...,
        sa.PrimaryKeyConstraint(
            "transaction_id", name=op.f("pk_foo_bar_versions")
        ),
    )
```

Here's a "normal" one:

```python
op.create_table(
        "bar_baz_versions",
       ...,
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_bar_baz_versions")
        ),
    )
```

Primary key cannot be duplicated, so it fails when two or more items are added within the same transaction, as the `transaction_id` is the primary key. As the simplest possible workaround I can see specifying a primary key on the association table. 

However, it's not clear how `SQLAlchemy-Continuum` should deal with this. Would it help if it raised an error earlier, when building the versions table? Or should it create a primary key column with an increment?

**Comment by killthekitten** [comment]
Also, it would help if @okcomp could share the code that adds items to the transaction. It looks like their original code should raise an error for both table-based and object-based definitions.

**Comment by maarten-dp** [comment]
Hi @killthekitten,

I indeed have no id on many-to-many tables, nor are my foreign keys flagged as primary keys in the version table, while they are primary keys in the original table.

I suppose it makes sense, but creates the issue of using the same transaction id as you explained.

My workaround is merely checking if records with this transaction id already exist while flushing/committing, and create a new transaction if there are. Drawback to this is that non-many-to-many tables are also impacted by this, and might generate unneeded transactions.

I feel like adding a dedicated primary key in the association table distorts the continuity of the version table with the table it's versioning, as well as the continuity with the other version tables. I think a better approach would be to recycle the primary keys of the original table. But I assume there's a reason for not having done this already?

**Comment by killthekitten** [comment]
@maarten-dp how do you generate your migrations? Do you have alembic set up? It won't automatically detect primary key changes in the original table, unless they were added when the table was first created. `SQLAlchemy-Continuum` won't do that either, so it requires some manual work.

**Comment by maarten-dp** [comment]
@killthekitten Yes, the migrations are done with alembic and the original tables started out with the correct primary keys.

If I understand correctly, you're telling me `SQLAlchemy-Continuum` is not able to transfer the original primary keys to the versioning table, and manually adding these primary keys to the versioning table would solve the problem?

If so, is it possible to have this behavior inherently in Continuum?

**Comment by killthekitten** [comment]
@maarten-dp my point is it's likely an alembic issue. Are you sure the primary keys were there from the beginning? Could you maybe share the original migration and the association table definition? Other info like SQLAlchemy / alembic versions might help too.

In my case this code generates a correct migration, but only when the migration is creating the table:

```python
join_table = Table(
    "questionnaires_uploads",
    DeclarativeBase.metadata,
    Column(
        "questionnaire_id",
        UUID(as_uuid=True),
        ForeignKey("questionnaires.id"),
        nullable=False,
        primary_key=True,
    ),
    Column(
        "upload_id",
        UUID(as_uuid=True),
        ForeignKey("uploads.id"),
        nullable=False,
        primary_key=True,
    ),
)
```

Could it be that alembic can't alter primary keys?

**Comment by maarten-dp** [comment]
I just had another look, and I understand better now.

The versioning table was indeed added by an alembic migration.

The Version model created by Continuum correctly flags the primary keys, but as you said, alembic doesn't pick them up when generating the migration script.

So in short, this issue is indeed generated by alembic. Thanks for your help @killthekitten

**Comment by maarten-dp** [comment]
I've made a small alembic migration script that fixes this issue, for anyone in need

```python
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy_continuum.version import VersionClassBase
from my_package import db
import inspect


def alter_version_model(klass, conn, ctx, metadata):
    table_name = klass.__table__.name
    pk_cols = [c.name for c in klass.__table__.columns if c.primary_key]

    existing_table = sa.Table(table_name, metadata, autoload_with=conn)
    existing_pk_cols = [c.name for c in existing_table.primary_key.columns]
    pkey = existing_table.primary_key.name

    if sorted(pk_cols) == sorted(existing_pk_cols):
        print('Nothing to do for {}'.format(table_name))
        return

    msg = 'Updating the PK of {} from {} to {}'
    print(msg.format(table_name, existing_pk_cols, pk_cols))

    op.drop_constraint(pkey, table_name)
    op.create_primary_key(pkey, klass.__table__.name, pk_cols)


def upgrade():
    conn = op.get_bind()
    ctx = op.get_context()
    metadata = sa.schema.MetaData()

    for klass in db.Model._decl_class_registry.values():
        if inspect.isclass(klass) and issubclass(klass, VersionClassBase):
            alter_version_model(klass, conn, ctx, metadata)


def downgrade():
    pass
```

I also confirm that running this migration script fixes my issues.

**Comment by ErikvdVen** [comment]
Came across this thread, while searching for a solution for this error:

```
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '10736-5-10971' for key 'PRIMARY'")
[SQL: INSERT INTO transaction_tags_version (transaction_id, tag_id, tx_id, operation_type) VALUES (%(transaction_id)s, %(tag_id)s, %(tx_id)s, %(operation_type)s)]
[parameters: {'transaction_id': 10736, 'tag_id': 5, 'tx_id': 10971, 'operation_type': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

It's just very odd, because the table is still empty and it complains about a duplicate entry. The only thing I could think about was: it tries to insert multiple statements at once, but I can't really find if that's true.

My code:

```
@router.get("/edit/{transaction_id}", tags=["transactions"])
@router.post("/edit/{transaction_id}", tags=["transactions"])
async def edit_transaction(
    request: Request, transaction_id: int, previous_page: str = None, db: Session = Depends(get_db)
):
    transaction = db.query(Transaction).filter(Transaction.id == transaction_id).first()
    if request.method == "POST":

        formdata = await request.form()
        tags = formdata.getlist("tags")

        # First remove the tags before adding them again
        transaction.tags = []

        for tag in tags:
            db_tag = db.query(Tag).filter(tag == Tag.alias).first()
            transaction.tags.append(db_tag)

        transaction.active = True
        if not formdata.get("active"):
            transaction.active = False

        db.commit()

        if previous_page:
            return RedirectResponse(
                previous_page, status.HTTP_303_SEE_OTHER
            )
        return RedirectResponse(
            "/transactions/", status.HTTP_303_SEE_OTHER
        )
```

It contains a many to many table as well as a Transaction can have multiple Tags. It's an existing project by the way, to which I've added sqlalchemy-continuum. At first, it automatically created all version tables, which seemed to work fine. 

Editing a single field works as well, except for the fact it adds two rows to the versioning table: one row with all columns filled, and one with all empty except for the id and transaction_id fields.

Any thoughts?

**Comment by alexfromapex** [comment]
This wasted a lot of my time so hopefully this helps someone:

When you generate migrations with Alembic, on your association table in the auto-generated migration code, you probably have something like this:

`sa.PrimaryKeyConstraint('transaction_id')`

And you just need to add the other primary key or foreign key columns, e.g.:

`sa.PrimaryKeyConstraint('column1','column2','transaction_id')`

And then downgrade and upgrade the migration again (not sure if this is needed)

**Comment by marksteward** [comment]
Is this specific to Continuum in some way?

**Comment by LennyLip** [comment]
Same here. There is one transation, but Insert add twice rows:
INSERT INTO user_chat (user_id, chat_id, adding_status) VALUES ($1::BIGINT, $2::BIGINT, $3::INTEGER)
=> [(505483666, 12, 0), (505483667, 12, 0)]
INSERT INTO user_chat_version (user_id, chat_id, adding_status, transaction_id, operation_type) VALUES ($1::BIGINT, $2::BIGINT, $3::INTEGER, $4::BIGINT, $5::SMALLINT)
(505483666, 12, 0, 340, 0)
INSERT INTO user_chat_version (user_id, chat_id, adding_status, transaction_id, operation_type) 
(505483667, 12, 0, 340, 0)

duplicate key value violates unique constraint "user_chat_version_pkey" 
DETAIL:  Key (transaction_id)=(340) already exists.

**The main issue is that the user_chat table lacks an initial PrimaryKeyConstraint.** 

pkey should be pk+transaction_id
