### ISSUE TITLE
check constraints from enums columns use the same name, and causes a conflict

### ISSUE THREAD

**Issue by harvimt** [kvesteri/sqlalchemy-continuum#180]
I'm using oracle, I'm not sure if that's a quirk of the DB (maybe other DBs allow check constraints on different tables to have the same name).

**Comment by rooterkyberian** [comment]
I seem to have a similar issue, but with Postgresql.

I wanted to add to existing database version tables and it breaks on the alembic autogenerated migrations 
```
class Source(Model):
    __tablename__ = 'source'
    __versioned__ = {}

    id = Column(db.String(100), primary_key=True)
    source_conditions = Column(db.Enum('yes', 'no', name='source_conditions_type'), nullable=False)
```

`flask db upgrade` (which calls alembic upgrade) fails as follows:
<details>
 <summary>Full traceback</summary>

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade fff551fffff8 -> fff7f37dfff4, Versioned Sources
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: type "source_conditions_type" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project-XXX/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/util/compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/user/dev/project-XXX/migrations/versions/d987f37d3354_versioned_sources.py", line 140, in upgrade
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/operations/ops.py", line 1120, in create_table
    return operations.invoke(op)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/alembic/ddl/impl.py", line 189, in create_table
    _ddl_runner=self)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 559, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1096, in _on_table_create
    t._on_table_create(target, bind, **kw)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1357, in _on_table_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1305, in create
    bind.execute(CreateEnumType(self))
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/user/.local/share/virtualenvs/project-XXX/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "source_conditions_type" already exists
 [SQL: "CREATE TYPE source_conditions_type AS ENUM ('yes', 'no')"] (Background on this error at: http://sqlalche.me/e/f405)
```
</summary>

I will likely modify the migration manually implementing workaround suggested in https://bitbucket.org/zzzeek/alembic/issues/53/create-table-dont-create-enum#comment-4100372

**Comment by LennyLip** [comment]
Same thing, are there any workarounds?
