### ISSUE TITLE
Flask, continuum, VersioningManager error

### ISSUE THREAD

**Issue by E179522** [kvesteri/sqlalchemy-continuum#191]
Have a Flask app using SQLAlchemy, Flask-Login.  Trying to integrate continuum but getting an error.  Can't manage to trace the issue from one file to the next:

```
Traceback (most recent call last):
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\transaction.py", line 138, in Transaction
    user_cls = registry[user_cls]
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36-32\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'User'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from isg import app
  File "C:\Users\xxxxx\Desktop\projects\isg\__init__.py", line 46, in <module>
    from isg import views, models
  File "C:\Users\xxxxx\Desktop\projects\isg\views.py", line 5, in <module>
    from .forms import *
  File "C:\Users\xxxxx\Desktop\projects\isg\forms.py", line 9, in <module>
    statenames = models.DropDowns.query.get(1).selections.split(',')
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask_sqlalchemy\__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\base.py", line 421, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\base.py", line 400, in _inspect_mapped_class
    mapper._configure_all()
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\mapper.py", line 1272, in _configure_all
    configure_mappers()
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\mapper.py", line 3044, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\event\attr.py", line 246, in __call__
    fn(*args, **kw)
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\events.py", line 621, in wrap
    fn(*arg, **kw)
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\builder.py", line 161, in configure_versioned_classes
    self.build_transaction_class()
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\builder.py", line 141, in build_transaction_class
    self.manager.create_transaction_model()
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\manager.py", line 166, in create_transaction_model
    self.transaction_cls = self.transaction_cls(self)
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\factory.py", line 11, in __call__
    return self.create_class(manager)
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\transaction.py", line 117, in create_class
    TransactionBase
  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\transaction.py", line 145, in Transaction
    'relationship ' % (user_cls, user_cls)
sqlalchemy_continuum.exc.ImproperlyConfigured: Could not build relationship between Transaction and User. User was not found
in declarative class registry. Either configure VersioningManager to use different user class or disable this relationship
```

pip freeze
alembic==0.9.9
beautifulsoup4==4.6.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.2.2
decorator==4.3.0
dicttoxml==1.7.4
dominate==2.3.1
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
flask-ldap-login==0.3.0
flask-ldap3-login==0.9.13
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
Jinja2==2.10
ldap3==2.5
mysqlclient==1.3.12
ntlm-auth==1.1.0
numpy==1.14.3
pandas==0.23.0
pyodbc==4.0.23
python-dateutil==2.7.3
pytz==2018.4
requests==2.18.4
SQLAlchemy==1.2.8
SQLAlchemy-Continuum==1.3.5
SQLAlchemy-Utils==0.33.3
WTForms==2.1

**models.py**
```
from sqlalchemy_continuum.plugins import FlaskPlugin
from sqlalchemy_continuum import make_versioned


make_versioned(plugins=[FlaskPlugin()])

@login.user_loader
def load_user(id):
    return Users.query.get(int(id))
	

class Users(UserMixin, db.Model):
	"""  Stores users info """
	__versioned__ = {}
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	first = db.Column(db.String(150))
	last = db.Column(db.String(150))
	fullname = db.Column(db.String(128), index=True, unique=False) #last, first
	name = db.Column(db.String(128), index=True, unique=True) #EID
	email = db.Column(db.String(255), unique=False)
	userlevel = db.Column(db.String(64), unique=False, default='Pending')
	def __repr__(self):
		return '<Users %r>' % (self.name)
```

**Comment by fuhrysteve** [comment]
See the docs for `make_versioned()`:

> By default Continuum tries to build a relationship between ‘User’ class and Transaction class. If you have differently named user class you can simply pass its name to make_versioned:
 ```python
make_versioned(user_cls='MyUserClass')
```

https://sqlalchemy-continuum.readthedocs.io/en/latest/configuration.html#customizing-transaction-user-class

You named your class `Users` (plural) instead of the default `User`. So you have two options:

1. rename your class to `User`
2. change the above to:

 ```python
make_versioned(user_cls='Users', plugins=[FlaskPlugin()])
```

@kvesteri this can be closed!

**Comment by E179522** [comment]
Silly mistake, my apologies.  However, after making the above edits, adding '__versioned__={}' to my tables, I now get a missing table error and items will not save

```
Traceback (most recent call last):
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\E179522\Desktop\projects\isg\decorators.py", line 31, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\E179522\Desktop\projects\isg\views.py", line 170, in isgEdit
    db.session.merge(eISG)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 1910, in merge
    self._autoflush()
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 1434, in _autoflush
    self.flush()
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
    self._flush(objects)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2281, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\event\attr.py", line 246, in __call__
    fn(*args, **kw)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\manager.py", line 340, in before_flush
    uow.process_before_flush(session)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\unit_of_work.py", line 71, in process_before_flush
    self.create_transaction(session)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\unit_of_work.py", line 121, in create_transaction
    self.version_session.flush()
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
    self._flush(objects)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
    flush_context.execute()
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
    rec.execute(self)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
    uow
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\MySQLdb\connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Users\E179522\Desktop\projects\crud\lib\site-packages\MySQLdb\connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.ProgrammingError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (1146, "Table 'rfc.transaction' doesn't exist") [SQL: 'INSERT INTO transaction (issued_at, remote_addr, user_id) VALUES (%s, %s, %s)'] [parameters: (datetime.datetime(2018, 7, 5, 13, 11, 6, 524368), '127.0.0.1', 28)] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by fuhrysteve** [comment]
You probably need to create it with `db.create_all()` or otherwise make an alembic migration.

**Comment by E179522** [comment]
db.create_all() did the trick.  Thank you.
