### ISSUE TITLE
Persistent loss of connection to DB on saving

### ISSUE THREAD

**Issue by E179522** [kvesteri/sqlalchemy-continuum#193]
I recently integrated continuum into my Flask application and having a recurring issue with the application having the DB connection closed.  This issue seems to only be appearing in my Windows dev environment, not on the production CentOS/uswgi/nginx box.

	Traceback (most recent call last):
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 2309, in __call__
		return self.wsgi_app(environ, start_response)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 2295, in wsgi_app
		response = self.handle_exception(e)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1741, in handle_exception
		reraise(exc_type, exc_value, tb)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\_compat.py", line 35, in reraise
		raise value
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 2292, in wsgi_app
		response = self.full_dispatch_request()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\_compat.py", line 35, in reraise
		raise value
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
		rv = self.dispatch_request()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask\app.py", line 1799, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
		return func(*args, **kwargs)
	  File "C:\Users\xxxxx\Desktop\projects\isg\decorators.py", line 31, in wrapper
		return f(*args, **kwargs)
	  File "C:\Users\xxxxx\Desktop\projects\isg\views.py", line 170, in isgEdit
		db.session.merge(eISG)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
		return getattr(self.registry(), name)(*args, **kwargs)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 1910, in merge
		self._autoflush()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 1434, in _autoflush
		self.flush()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
		self._flush(objects)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2281, in _flush
		self.dispatch.before_flush(self, flush_context, objects)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\event\attr.py", line 246, in __call__
		fn(*args, **kw)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\manager.py", line 340, in before_flush
		uow.process_before_flush(session)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\unit_of_work.py", line 71, in process_before_flush
		self.create_transaction(session)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\unit_of_work.py", line 121, in create_transaction
		self.version_session.flush()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
		self._flush(objects)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
		transaction.rollback(_capture_exception=True)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
		compat.reraise(exc_type, exc_value, exc_tb)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
		raise value
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
		flush_context.execute()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
		rec.execute(self)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
		uow
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
		mapper, table, insert)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\persistence.py", line 865, in _emit_insert_statements
		result = cached_connections[connection].\
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\_collections.py", line 729, in __missing__
		self[key] = val = self.creator(key)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\orm\persistence.py", line 1268, in <lambda>
		compiled_cache=base_mapper._compiled_cache
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 317, in execution_options
		self.dispatch.set_connection_execution_options(c, opt)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\event\attr.py", line 284, in __call__
		fn(*args, **kw)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy_continuum\manager.py", line 412, in track_cloned_connections
		if connection.connection is c.connection:  # ConnectionFairy is the same - this is a clone
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 354, in connection
		self._handle_dbapi_exception(e, None, None, None, None)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in _handle_dbapi_exception
		util.reraise(*exc_info)
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
		raise value
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 352, in connection
		return self._revalidate_connection()
	  File "C:\Users\xxxxx\Desktop\projects\crud\lib\site-packages\sqlalchemy\engine\base.py", line 432, in _revalidate_connection
		raise exc.ResourceClosedError("This Connection is closed")
	sqlalchemy.exc.ResourceClosedError: This Connection is closed

Pip Freeze:
alembic==0.9.9
asn1crypto==0.24.0
bcrypt==3.1.4
beautifulsoup4==4.6.0
bleach==2.1.3
blinker==1.4
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.2.2
decorator==4.3.0
dicttoxml==1.7.4
dominate==2.3.1
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
flask-ldap-login==0.3.0
flask-ldap3-login==0.9.13
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
html5lib==1.0.1
icalendar==4.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
ldap3==2.5
lxml==4.2.1
Mako==1.0.7
MarkupSafe==1.0
mysqlclient==1.3.12
ntlm-auth==1.1.0
numpy==1.14.3
pandas==0.23.0
paramiko==2.4.1
pyasn1==0.4.3
pyasn1-modules==0.2.1
pycparser==2.18
PyNaCl==1.2.1
pyodbc==4.0.23
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2018.4
requests==2.18.4
requests-ntlm==1.1.0
sharepoint==0.4.2
six==1.11.0
SQLAlchemy==1.2.8
SQLAlchemy-Continuum==1.3.5
SQLAlchemy-Utils==0.33.3
tqdm==4.23.4
untangle==1.1.1
urllib3==1.22
visitor==0.1.3
webencodings==0.5.1
Werkzeug==0.14.1
wget==3.2
wtf-tinymce==0.1.3
WTForms==2.1
xlrd==1.1.0
xmltodict==0.11.0

**Comment by fuhrysteve** [comment]
Duplicate of #188
