### ISSUE TITLE
column_property isn't ignored when reverting

### ISSUE THREAD

**Issue by marksteward** [kvesteri/sqlalchemy-continuum#197]
In a table with a column_property, it looks like revert() tries to restore the generated column as well, which it shouldn't do.

```
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.orm import sessionmaker, configure_mappers, column_property
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy_continuum import make_versioned

engine = create_engine('sqlite://')
Session = sessionmaker(engine)
Base = declarative_base(engine)

make_versioned()

class User(Base):
    __versioned__ = {}
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True, autoincrement=True)
    first_name = Column(String)
    last_name = Column(String)

    full_name = column_property(first_name + last_name)

configure_mappers()

if __name__ == '__main__':
    Base.metadata.create_all()

    session = Session()
    u = User(first_name='test', last_name='tester')
    session.add(u)
    session.commit()

    u.versions[0].revert()
```

This throws:

```
Traceback (most recent call last):
  File "continuum-test.py", line 32, in <module>
    u.versions[0].revert()
  File ".../lib/python3.5/site-packages/sqlalchemy_continuum/version.py", line 71, in revert
    return Reverter(self, relations=relations)()
  File ".../lib/python3.5/site-packages/sqlalchemy_continuum/reverter.py", line 125, in __call__
    self.revert_properties()
  File ".../lib/python3.5/site-packages/sqlalchemy_continuum/reverter.py", line 48, in revert_properties
    getattr(self.obj, prop.key)
AttributeError: 'UserVersion' object has no attribute 'full_name'
```

Happy to add a filter based on inspect to fix this, but raising here first in case there's a more obvious fix.

**Comment by marksteward** [comment]
Just realised that adding `__versioned__ = {'exclude': ['full_name']}` is a workaround, so I can presumably add the filter where that's implemented.
