### ISSUE TITLE
sqlalchemy.exc.ArgumentError: Can't add additional column 'post_version_id' when specifying __table__

### ISSUE THREAD

**Issue by ErinMorelli** [kvesteri/sqlalchemy-continuum#212]
I have an existing database and models that I am looking to add SQLAlchemy-Continuum to, but I'm running into this error:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    from database.models import Post
  File "/home/erin/projects/blog/database/__init__.py", line 12, in <module>
    from models import *
  File "/home/erin/projects/blog/database/models.py", line 669, in <module>
    sa.orm.configure_mappers()
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 3210, in configure_mappers
    Mapper.dispatch._for_class(Mapper).after_configured()
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/orm/events.py", line 637, in wrap
    fn(*arg, **kw)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 167, in configure_versioned_classes
    self.build_models()
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy_continuum/builder.py", line 89, in build_models
    self.manager.transaction_cls
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy_continuum/model_builder.py", line 274, in __call__
    self.version_class = self.build_model(table)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy_continuum/model_builder.py", line 262, in build_model
    return type(name, self.base_classes(), args)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 71, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 128, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 156, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 184, in __init__
    self._setup_table()
  File "/home/erin/projects/blog/build/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 543, in _setup_table
    "specifying __table__" % c.key
sqlalchemy.exc.ArgumentError: Can't add additional column 'post_version_id' when specifying __table__
```

I'm calling `make_versioned()` at the top of my `models.py` file and calling `configure_mappers()` at the bottom after all of my models are defined, just like in all of the documentation examples.

The only table I have added versioning to is called Post, but I have several other tables declared as well.

```
class Post(mixins.StatusMixin, mixins.LastModifiedMixin, mixins.CreatedMixin, ModelBase):
    __versioned__ = {}
    __tablename__ = 'posts'

    title = sa.Column('title', sa.String(255), nullable=False)
    body = sa.Column('body', sa.Text, nullable=True)
    isPrivate = sa.Column('is_private', sa.Boolean, default=False, nullable=False)
    link = sa.Column('link', sau.URLType, nullable=True)
```

I'm struggling to trace where this error might be coming from. Any ideas?

Thanks!

**Comment by ErinMorelli** [comment]
Turns out this was not an issue with SQLAlchemy-Continuum, it was due to how I had my ModelBase class configured. I was trying to add an extra column to the version table. Removing that fixed the problem.
