### ISSUE TITLE
Transaction table not being created.

### ISSUE THREAD

**Issue by dvschramm** [kvesteri/sqlalchemy-continuum#234]
Pyramid/SQLAlchemy project, using alembic the version tables are being created fine but the Transaction table is not so when changes are made, I get the error:

`ProgrammingError: (psycopg2.ProgrammingError) relation "transaction" does not exist
LINE 1: INSERT INTO transaction (fxt, issued_at, id, remote_addr) VA...
                    ^
 [SQL: "INSERT INTO transaction (fxt, issued_at, id, remote_addr) VALUES (%(fxt)s, %(issued_at)s, nextval('transaction_id_seq'), %(remote_addr)s) RETURNING transaction.id"] [parameters: {'fxt': None, 'issued_at': datetime.datetime(2020, 1, 28, 23, 1, 46, 849596), 'remote_addr': None}] (Background on this error at: http://sqlalche.me/e/f405)
`
Not doing anything fancy, just using the make_versioned/configure_mappers calls as in the examples.

**Comment by dvschramm** [comment]
I just created the table in an alembic migration.

**Comment by KeironO** [comment]
Hey there,

Do you happen to have a fix for this?

Best wishes,

Keiron

**Comment by killthekitten** [comment]
@KeironO could share some of your code to reproduce bug, i.e. show how you setup `sqlalchemy-continuum` and create a migration?

**Comment by KeironO** [comment]
It's quite convoluted due to the size of the project, I don't know how I can go about producing a small enough example that you're willing to look through.

**Comment by killthekitten** [comment]
@KeironO you could use the [minimal application](https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#a-minimal-application) section of the Flask-Sqlalchemy guide for example. It's pretty short.

**Comment by KeironO** [comment]
I've been unable to recreate the problem using the minimal application.

@dvschramm noted that he `created the table in an alembic migration`, but I don't know how to do that?

**Comment by killthekitten** [comment]
@KeironO sure, let's debug it step by step. Let me know if it's too detailed, or if something is unclear.

- Do you use SQLAlchemy with [alembic](https://alembic.sqlalchemy.org/en/latest/), and both are set up and working fine?
- If you use SQLAlchemy through the `Flask-SQLAlchemy` extension, do you have the `flask db migrate` command available? It will create a migration file each time you run it from the command line, that's the migration @dvschramm is referring to.
- If you don't have it, how do you usually update the database?
- Did you follow the [installation guide](https://sqlalchemy-continuum.readthedocs.io/en/latest/intro.html#installation) for `SQLAlchemy-Continuum`? Important pieces are: where do you place the call to `make_versioned` and `sa.orm.configure_mappers()`, and whether you've marked a model `__versioned__`.  

Normally, after the steps above, the first call to `flask db migrate` would generate a migration that looks like this:
 
```python
   """Add SQLAlchemy Continuum

Revision ID: -------
Revises: ------

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "------"
down_revision = "-------"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction")),
    )


def downgrade():
    op.drop_table("transaction")
```

If it wasn't created automatically, you can add this migration manually. Run `flask db revision` and copy `upgrade`/`downgrade` to the newly created file. I believe that's what @dvschramm noted as `created the table...`.

**Comment by KeironO** [comment]
Hey there,

Thank you for your response.

> Do you use SQLAlchemy with alembic, and both are set up and working fine?

In standard use, yes.

> If you use SQLAlchemy through the Flask-SQLAlchemy extension, do you have the flask db migrate command available? It will create a migration file each time you run it from the command line, that's the migration @dvschramm is referring to.

I do use Flask-SQLAlchemy, but..

> If you don't have it, how do you usually update the database?

I use alembic.

> Did you follow the installation guide for SQLAlchemy-Continuum? Important pieces are: where do you place the call to make_versioned and sa.orm.configure_mappers(), and whether you've marked a model __versioned__.

I believe so, but I use a different structure to the example being. I was having recursive import issues when importing models, so I broke it all out.

The init file looks like:

```python
from __future__ import absolute_import

from .database import db

from flask import Flask

from .commands import cmd_setup as cmd_setup_blueprint
from .api import api as api_blueprint
from .setup import setup as setup_blueprint
from .misc import misc as misc_blueprint
from .auth import auth as auth_blueprint
from .attribute import attribute as attribute_blueprint
from .document import document as document_blueprint
from .consent import consent as consent_blueprint
from .protocol import protocol as protocol_blueprint
from .sample import sample as sample_blueprint
from .tmpstore import tmpstore as tmpstore_blueprint
from .storage import storage as storage_blueprint

from app.errors import error_handlers

from .extensions import register_extensions, register_apispec


def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile("config.py")

    register_extensions(app)
    register_blueprints(app)
    register_error_handlers(app)
    register_apispec(app)

    return app


def register_error_handlers(app):
    for error_handler in error_handlers:
        app.register_error_handler(
            error_handler["code_or_exception"], error_handler["func"]
        )


def register_blueprints(app):
    app.register_blueprint(cmd_setup_blueprint)
    app.register_blueprint(api_blueprint, url_prefix="/api")
    app.register_blueprint(setup_blueprint, url_prefix="/setup")
    app.register_blueprint(misc_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix="/auth")
    app.register_blueprint(attribute_blueprint, url_prefix="/attribute")
    app.register_blueprint(document_blueprint, url_prefix="/document")
    app.register_blueprint(consent_blueprint, url_prefix="/consent")
    app.register_blueprint(protocol_blueprint, url_prefix="/protocol")
    app.register_blueprint(sample_blueprint, url_prefix="/sample")
    app.register_blueprint(tmpstore_blueprint, url_prefix="/tmpstore")
    app.register_blueprint(storage_blueprint, url_prefix="/storage")


def setup_database(app):
    with app.app_context():
        db.create_all()

```

Where database.py looks like:

```
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import configure_mappers

from sqlalchemy_continuum import make_versioned
make_versioned(user_cls=None)

db = SQLAlchemy()

from .base import BaseModel

Base = declarative_base(cls=BaseModel)
Base.query = db.session.query_property()

from .auth.models import *
from .misc.models import *
from .attribute.models import *
from .consent.models import *
from .document.models import *
from .protocol.models import *
from .sample.models import *
from .tmpstore.models import *
from .storage.models import *


configure_mappers()
```

Right now, I only have Document being versioned.

```
class Document(Base, RefAuthorMixin, RefEditorMixin):
    __versioned__ = {}
    
    name = db.Column(db.String, nullable=False)
    description = db.Column(db.String)
    type = db.Column(db.Enum(DocumentType), nullable=False)
    files = db.relationship("DocumentFile", backref="documentfile")
```

And when I create the database using alembic:

```
alembic revision --autogenerate -m 'gen'; alembic upgrade head
```

I get the following output:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'consentformtemplate_version'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_consentformtemplate_version_end_transaction_id' on '['end_transaction_id']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_consentformtemplate_version_operation_type' on '['operation_type']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_consentformtemplate_version_transaction_id' on '['transaction_id']'
INFO  [alembic.autogenerate.compare] Detected added table 'document_version'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_document_version_end_transaction_id' on '['end_transaction_id']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_document_version_operation_type' on '['operation_type']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_document_version_transaction_id' on '['transaction_id']'
INFO  [alembic.autogenerate.compare] Detected added table 'useraccount'
INFO  [alembic.autogenerate.compare] Detected added table 'useraccount_version'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_useraccount_version_end_transaction_id' on '['end_transaction_id']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_useraccount_version_operation_type' on '['operation_type']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_useraccount_version_transaction_id' on '['transaction_id']'
INFO  [alembic.autogenerate.compare] Detected added table 'address'
INFO  [alembic.autogenerate.compare] Detected added table 'attribute'
INFO  [alembic.autogenerate.compare] Detected added table 'consentformtemplate'
INFO  [alembic.autogenerate.compare] Detected added table 'document'
INFO  [alembic.autogenerate.compare] Detected added table 'protocoltemplate'
INFO  [alembic.autogenerate.compare] Detected added table 'sampledisposal'
INFO  [alembic.autogenerate.compare] Detected added table 'sampletocontainer'
INFO  [alembic.autogenerate.compare] Detected added table 'temporarystore'
INFO  [alembic.autogenerate.compare] Detected added table 'useraccounttoken'
INFO  [alembic.autogenerate.compare] Detected added table 'attributenumericsetting'
INFO  [alembic.autogenerate.compare] Detected added table 'attributeoption'
INFO  [alembic.autogenerate.compare] Detected added table 'attributetextsetting'
INFO  [alembic.autogenerate.compare] Detected added table 'consentformtemplatequestion'
INFO  [alembic.autogenerate.compare] Detected added table 'documentfile'
INFO  [alembic.autogenerate.compare] Detected added table 'protocoltemplatetodocument'
INFO  [alembic.autogenerate.compare] Detected added table 'protocoltext'
INFO  [alembic.autogenerate.compare] Detected added table 'sampleconsent'
INFO  [alembic.autogenerate.compare] Detected added table 'sampleprotocolevent'
INFO  [alembic.autogenerate.compare] Detected added table 'sampletotype'
INFO  [alembic.autogenerate.compare] Detected added table 'siteinformation'
INFO  [alembic.autogenerate.compare] Detected added table 'attributedata'
INFO  [alembic.autogenerate.compare] Detected added table 'building'
INFO  [alembic.autogenerate.compare] Detected added table 'sample'
INFO  [alembic.autogenerate.compare] Detected added table 'sampleconsentanswer'
INFO  [alembic.autogenerate.compare] Detected added table 'room'
INFO  [alembic.autogenerate.compare] Detected added table 'sampledocument'
INFO  [alembic.autogenerate.compare] Detected added table 'samplereview'
INFO  [alembic.autogenerate.compare] Detected added table 'sampletocustomattributedata'
INFO  [alembic.autogenerate.compare] Detected added table 'subsampletosample'
INFO  [alembic.autogenerate.compare] Detected added table 'coldstorage'
INFO  [alembic.autogenerate.compare] Detected added table 'coldstorageshelf'
INFO  [alembic.autogenerate.compare] Detected added table 'documenttocoldstorage'
INFO  [alembic.autogenerate.compare] Detected added table 'samplerack'
INFO  [alembic.autogenerate.compare] Detected added table 'entitytostorage'
  Generating /limbus/migrations/versions/e7b02f752412_gen.py ...  done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e7b02f752412, gen
```

But when I attempt to modify the database, I get the following error:

```
psycopg2.errors.UndefinedTable: relation "transaction" does not exist
LINE 1: INSERT INTO transaction (issued_at, is_locked, id, remote_ad...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/limbus/app/commands/setup.py", line 67, in create_kryten
    db.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
   self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2525, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy_continuum/manager.py", line 340, in before_flush
    uow.process_before_flush(session)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy_continuum/unit_of_work.py", line 71, in process_before_flush
    self.create_transaction(session)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy_continuum/unit_of_work.py", line 121, in create_transaction
    self.version_session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "transaction" does not exist
LINE 1: INSERT INTO transaction (issued_at, is_locked, id, remote_ad...
                    ^

[SQL: INSERT INTO transaction (issued_at, is_locked, id, remote_addr) VALUES (%(issued_at)s, %(is_locked)s, nextval('transaction_id_seq'), %(remote_addr)s) RETURNING transaction.id]
[parameters: {'issued_at': datetime.datetime(2020, 11, 7, 11, 17, 59, 731004), 'is_locked': False, 'remote_addr': None}]
(Background on this error at: http://sqlalche.me/e/f405)
```

Apologies if this is quite convoluted, but I've been struggling with this for awhile now :)

**Comment by killthekitten** [comment]
@KeironO Looks about right! Where do you call `setup_database` from? You don't usually need to call `create_all` when you use alembic for migrations. You would create migrations model by model and commit them to the repo. 

Do you run the whole setup in docker? And do you run alembic and the app using the same database? Sometimes the database available from CLI is a different database then the flask app's one.   

In any case, my short suggestion would be: generate a second migration file, copy the code that creates the transaction table (the one I posted in the previous message), migrate the database again and move on with your life. Once the transaction table is created, you shouldn't have any problems.

In case you want to debug it, take some time to figure out the order of loading. When you call alembic commands, it all starts from the configuration file (`migrations/env.py` in my case), and not the usual flask directory structure. 

While inspecting my own codebase, I've found an explicit import of the models in the alembic `env.py` file -- just the same that is in your `db.py`. I might have added that while fixing a similar issue. This means the order of loading in my case is 1) env.py, 2) models, 3) db.py.

**Comment by KeironO** [comment]
For whatever reason, I wasn't notified of your response. I'll attempt to apply the fixes you've suggested today.

Thank you !!

**Comment by KeironO** [comment]
Oh wow, that was easy.

So, I created a table as I would any other:

```
class Transaction(Base):
    issued_at = db.Column(db.DateTime(), nullable=True)
    remote_addr = db.Column(db.String(50), nullable=True)
```

And it works :D

Thank you, just need to get it to play nicely with marshmallow and we're off to the races.

**Comment by zupo** [comment]
If anyone is still looking for how to integrate SQLAlchemy-Continuum with Pyramid, here's an example repo: https://github.com/zupo/tutorial/tree/exploration/sqlalchemy-continuum
